Update README.md
step-up-labs/spayd-kmp pull request #1
Opened 2024-12-17 19:42 UTC by baradrb

English proofreading

2024-12-18 11:42 UTC, davidvavra requested changes

2024-12-18 11:42 UTC, davidvavra commented on README.md
> +    account = Account(iban = CZ7603000000000076327632),
Tady chybí string uvozovky

2024-12-18 11:42 UTC, davidvavra commented on README.md
> +    Key.ACCOUNT to Account(iban = CZ7603000000000076327632),
Taky

2024-12-18 11:42 UTC, davidvavra commented on README.md
> +    Key.ACCOUNT to Account(iban = CZ7603000000000076327632),
Taky

2024-12-18 11:42 UTC, davidvavra commented on README.md
> +For any contributions, make sure all unit tests pass. Ideally, add a new unit test. Any contributions via pull requests are welcome.
Klidně ať přidají víc testů, nejenom jeden.

2024-12-18 22:09 UTC, baradrb reviewed
I resolved your comments.

2024-12-19 11:35 UTC, davidvavra approved these changes

2024-12-19 11:35 UTC, merged